"""Figure prose bindings for deterministic figures."""

from __future__ import annotations

from red_line.analysis.evidence_sensitivity import run_evidence_sensitivity
from red_line.analysis.monotonicity import run_monotonicity_sweep
from red_line.analysis.registry_metrics import (
    EVIDENCE_KIND_COLUMNS,
    exemption_evidence_matrix,
    line_summaries,
    scope_token_membership,
    severity_distribution,
    tier_floor_distribution,
    unevidenced_exemptions,
)
from red_line.analysis.trigger_semantics import run_trigger_semantics
from red_line.registry.lines import PERSONAL_RED_LINES

# Live-derived counts used inside FIGURE_TEXT below, so registry captions and
# alt text can never silently drift from the registry or analysis modules.
_LINE_COUNT = len(PERSONAL_RED_LINES)
_EXEMPTION_ROW_COUNT = len(exemption_evidence_matrix())
_EVIDENCE_KIND_COUNT = len(EVIDENCE_KIND_COLUMNS)
_MONOTONICITY = run_monotonicity_sweep()
_SUMMARIES = line_summaries()
_MEMBERSHIP = scope_token_membership()
_SHARED_TOKENS = tuple(token for token, owners in _MEMBERSHIP if len(owners) > 1)
_FREE_PASS_COUNT = len(unevidenced_exemptions())
_SENSITIVITY = run_evidence_sensitivity()
_TRIGGERS = run_trigger_semantics()
_SEVERITY_SPLIT = " · ".join(
    f"{severity.value.upper()} {count}" for severity, count in severity_distribution().items()
)
_FLOOR_SPLIT = " · ".join(
    f"{tier.value.replace('_', '-').upper()} {count}" for tier, count in tier_floor_distribution().items()
)


FIGURE_TEXT = {
    "fig:governance-architecture": {
        "filename": "governance_architecture.png",
        "title": "A personal refusal becomes an evidence-gated review record",
        "caption": (
            "Deterministic architecture schematic generated by "
            "scripts/build_figures.py from the registry, intake, evaluation, "
            "oversight, and canary interfaces. The local author boundary "
            f"contains the six drawn stages: the {_LINE_COUNT}-line beacon, the "
            "action-declaration intake, the evidence gate, the policy match "
            "over lines and typed exemptions, the transparency tally, and the "
            "canary check. A recorded outcome can be tallied for transparency "
            "and bound to a dated canary statement; only the external-witness "
            "side of the boundary can supply the independent prior copy that "
            "makes a silent edit observable. Arrows describe data and "
            "accountability flow, not automated enforcement. In particular, the "
            "evaluator does not stop execution, the tally does not create a "
            "third-party audit, and the canary does not prevent a malicious "
            "re-issuance. The figure is a method diagram, not evidence that a "
            "real engagement passed review."
        ),
        "alt": "Flow from registry commitment through action evaluation and self-review to transparency, canary, and an external witness.",
        "source": "src/red_line/registry, src/red_line/evaluation, src/red_line/oversight, and src/red_line/canary",
    },
    "fig:oversight-tier-ladder": {
        "filename": "oversight_tier_ladder.png",
        "title": "Less retained oversight narrows the release envelope",
        "caption": (
            "Registry-derived tier matrix. Each row is one current red line and "
            "each filled cell marks a deployment tier at or above that line's "
            "minimum oversight floor; an empty cell is not permission to ignore "
            "the line, but indicates that the line's subject matter cannot be "
            "released at that lower-oversight tier. HOSTED retains author-operated "
            "observation and withdrawal, CONNECTED retains a maintained update or "
            "suspension path, and AIR-GAPPED means beyond recall. The two CANARY "
            "rows are visibly pinned away from AIR-GAPPED release by the registry "
            "invariant. The diagram represents eligibility thresholds, not a "
            "probability of safety or a claim that retained oversight is itself "
            "sufficient. A hard-blocked action remains non-compliant at every "
            "tier; the tier floor only adds an aggravating reason or constrains a "
            "carve-out."
        ),
        "alt": "Matrix showing seven red lines and the hosted, connected, and air-gapped tiers allowed by each line's oversight floor.",
        "source": "src/red_line/registry/lines.py and src/red_line/model/enums.py",
    },
    "fig:evaluation-decision-path": {
        "filename": "evaluation_decision_path.png",
        "title": "Normalization and evidence gates precede every policy verdict",
        "caption": (
            "Decision-path schematic generated from the strict evaluate_action "
            "contract. Scope is first normalized through NFKC, an ASCII boundary, "
            "and explicit aliases; malformed tokens stop at INSUFFICIENT_INFORMATION "
            "rather than creating vocabulary. A mandatory ActionContext and verified "
            "evidence gate then come before policy matching. Missing, unknown, ambiguous, "
            "self-asserted, stale, or contradicted context stops at INSUFFICIENT_INFORMATION. "
            "A complete action with no implicated line is OUTSIDE_SCOPE, not "
            "COMPLIANT. Only a typed exemption with verified evidence can narrow "
            "an implicated line; multiple prohibited dimensions or a tier deficit "
            "require modification. The path remains lexical and is not a semantic "
            "safety classifier."
        ),
        "alt": "Decision flow from scope normalization through mandatory evidence, typed exemptions, tier checks, and five distinct outcomes.",
        "source": "src/red_line/evaluation/evaluator.py, src/red_line/model/action.py, and src/red_line/model/red_line.py",
    },
    "fig:canary-trust-boundary": {
        "filename": "canary_trust_boundary.png",
        "title": "The canary detects drift only when a prior copy is outside the writer's reach",
        "caption": (
            "Trust-boundary schematic for the canary mechanism. At issuance, the "
            "registry is canonicalized into an aggregate digest and per-line "
            "metadata; verification later compares those values with the live "
            "registry and checks freshness. A removed or modified CANARY-grade line "
            "is escalated, while a stale, future-dated, or malformed attestation "
            "fails closed. The drawn re-issuance guard records that issue_canary "
            "refuses a silent successor for a changed registry unless a rationale "
            "is supplied; that guard binds only the honest, in-process path. The "
            "dashed boundary is the critical security condition: "
            "the prior statement must be held by someone or some system that cannot "
            "be rewritten by the same author who edits the registry. The visual "
            "also marks the negative space of the claim. A canary cannot detect a "
            "semantic violation hidden by misleading scope labels, cannot stop an "
            "author from re-issuing a new statement, and cannot enforce an action "
            "finding. It is tamper evidence conditional on an independent witness, "
            "not prevention or legal protection."
        ),
        "alt": "Trust boundary showing registry hashing, external prior copy, and verification outputs, with explicit undetected cases.",
        "source": "src/red_line/canary/hashing.py, src/red_line/canary/statement.py, and src/red_line/canary/verification.py",
    },
    "fig:scholarship-reading-map": {
        "filename": "scholarship_reading_map.png",
        "title": "The method is assembled from many situated questions, not one universal lineage",
        "caption": (
            "Curated reading map for the method's conceptual audit. The cards group "
            "primary texts, historical scholarship, critical methodology, and "
            "contemporary standards by broad period and identify the question each "
            "source contributes: intelligence and deception, law and authority, "
            "social cohesion, institutional self-governance, research power, "
            "contextual privacy, sociotechnical abstraction, decolonial foresight, "
            "collective data authority, or operational risk management. The map "
            "includes Latin American colonial-encounter and Indigenous data-sovereignty "
            "sources alongside the Black Atlantic and other situated "
            "voices. Their placement is not a genealogy of "
            "direct influence, a ranking of traditions, or evidence that these "
            "authors would endorse this personal framework. Several works contain "
            "hierarchical, coercive, exclusionary, or historically bounded elements; "
            "the manuscript cites them selectively and names those limits. The map "
            "is therefore a provenance and humility device: it makes the reading "
            "base more geographically and historically plural while keeping the "
            "project's own normative choices distinct from its sources."
        ),
        "alt": "Non-linear reading map with situated sources from China, India, Greece, the Islamic world, North Africa, Europe, Latin America, Aotearoa, Africa, and global institutions, including collective data-governance questions.",
        "source": "docs/research-method.md and manuscript/references.bib",
        "source_ids": (
            "sunzi1910artofwar",
            "kautilya2013arthasastra",
            "aristotle350politics",
            "mahdi2000farabipolitical",
            "darling2007asabiyya",
            "machiavelli1513prince",
            "wollstonecraft1792vindication",
            "cugoano1787thoughts",
            "lascasas1552brief",
            "ostrom1990commons",
            "scott1998seeingstate",
            "smith1999decolonizing",
            "kukutaitaylor2016ids",
            "nissenbaum2004contextual",
            "jobin2019global",
            "birhane2020colonization",
            "mohamed2020decolonial",
            "unesco2021recommendation",
            "oecd2019principles",
            "tabassi2023airmf",
        ),
    },
    "fig:line-set-compass": {
        "filename": "line_set_compass.png",
        "title": "Four questions keep refusal, method, aspiration, and absence distinct",
        "caption": (
            "Orientation schematic for the four-line set. Red Line is the refusal "
            "boundary and explicit No document; Black Line is the positive wire "
            "for strong, concise, intelligent work; Golden Line is an aspirational "
            "direction rather than a pass/fail rule; and White Line records what is "
            "absent, withheld, uncertain, or left outside a claim. The colors are "
            "semantic accents, not severity scores. The four works are standalone "
            "instruments with different registries and evaluators, and the figure "
            "does not imply that one line can substitute for another."
        ),
        "alt": "Four labeled panels distinguish Red refusal, Black method, Golden aspiration, and White absence, with arrows showing cross-reference without substitution.",
        "source": "../../docs/line-set.md (sidecar line-set map) and manuscript/02b_line_set_orientation.md",
    },
    "fig:outcome-precedence": {
        "filename": "outcome_precedence_ladder.png",
        "title": "The evaluator returns the single most severe applicable outcome",
        "caption": (
            "Outcome-precedence ladder generated from the evaluate_action control "
            "flow. The intake gate is a short circuit: any missing, unverified, "
            "stale, or malformed-scope field returns INSUFFICIENT_INFORMATION "
            "before policy matching begins. If the intake is complete and "
            "evidenced, the evaluator reduces over the implicated lines to one "
            "classification, ordered by severity: a hard block (an implicated line "
            "with no verified exemption) dominates a modification requirement (a "
            "verified exemption with two or more prohibited dimensions or a use "
            "below the tier floor), which dominates a fully narrowed compliant "
            "result, which dominates OUTSIDE_SCOPE when no line is implicated. A "
            "less severe outcome never overrides a more severe one. The ladder is "
            "a control-flow schematic, not empirical evidence that any particular "
            "action was safe, lawful, or correctly described."
        ),
        "alt": "Vertical precedence ladder: an insufficient-information short circuit above a severity-ordered reduction to non-compliant, requires-modification, compliant, and outside-scope.",
        "source": "src/red_line/evaluation/evaluator.py",
    },
    "fig:scholarship-transfer-matrix": {
        "filename": "scholarship_transfer_matrix.png",
        "title": "Every source transfer carries a question and a stopping point",
        "caption": (
            "Deterministic source-ledger matrix. Each row represents a situated "
            "source family and records the question transferred into Red Line, "
            "the claim class it can support, and the boundary beyond which the "
            "source is not being used. The matrix is a documentation device, not "
            "a ranking of traditions, a coverage score, or proof that the sources "
            "agree. Historical and geographically diverse works remain distinct; "
            "their placement beside one another widens the audit questions without "
            "creating a universal lineage. Collective data authority is kept "
            "distinct from individual consent."
        ),
        "alt": "Matrix of situated source families, transferred questions, claim classes, and explicit interpretation limits.",
        "source": "docs/research-method.md and manuscript/references.bib",
        "source_ids": (
            "sunzi1910artofwar",
            "kautilya2013arthasastra",
            "mahdi2000farabipolitical",
            "darling2007asabiyya",
            "cugoano1787thoughts",
            "wollstonecraft1792vindication",
            "smith1999decolonizing",
            "kukutaitaylor2016ids",
            "birhane2020colonization",
            "unesco2021recommendation",
            "au2022datapolicy",
            "tabassi2023airmf",
        ),
    },
    "fig:improvement-method-loop": {
        "filename": "improvement_method_loop.png",
        "title": "An evidence-gated improvement loop keeps claim, action, and artifact boundaries aligned",
        "caption": (
            "First-principles and science workflow schematic for this improvement pass. "
            "The loop begins by deconstructing the actual function, challenges hidden "
            "assumptions and authority, declares a claim class with an evidence state "
            "and stopping point, reconstructs the smallest honest action protocol, "
            "evaluates it fail-closed, freezes the result, and verifies source-to-render "
            "bindings before revision. The outer dashed boundary marks the local artifact; "
            "an external witness, semantic truth, legal judgment, and real-world outcome "
            "remain outside it. This is a reproducible method map, not a measurement of "
            "safety, understanding, or improvement effect."
        ),
        "alt": "A bounded loop from deconstruction and challenge through claim declaration, reconstruction, fail-closed evaluation, frozen records, artifact verification, and revision; semantic truth and external witnessing remain outside the boundary.",
        "source": "docs/improvement_protocol.md, docs/decision-protocol.md, data/claim_register.json, and scripts/quality_gate.py",
    },
    "fig:boundary-instrument-plate": {
        "filename": "boundary_instrument_plate.png",
        "title": "A boundary is an instrument: declare, evidence, stop, witness",
        "caption": (
            "Editorial plate generated from the live Red Line registry and evaluator "
            "interfaces. Three labelled traces — the declaration, the evidence demand, "
            f"and the {_LINE_COUNT}-line commitment boundary — feed a local review; the "
            f"{_EVIDENCE_KIND_COUNT} required intake dimensions appear as a labelled "
            "field derived from the live evidence-kind enum; "
            "the five evaluator outcomes remain distinct; and the red vertical boundary "
            "separates a locally recorded result from the external witness required for "
            "change detection. The paper, curves, registration marks, and color are visual "
            "rhetoric derived from the project's cover language, not measurements. This "
            "plate does not demonstrate semantic understanding, legal validity, independent "
            "truth, enforcement, or real-world safety."
        ),
        "alt": (
            "Art-directed boundary instrument: declaration, evidence, and boundary "
            "traces converge on a local review beside a red commitment line, a "
            "labelled field lists the required intake dimensions, and five outcome "
            "nodes with an external prior witness sit beyond the boundary."
        ),
        "source": "src/red_line/registry/lines.py, src/red_line/model/action.py, src/red_line/model/enums.py, and src/red_line/canary/verification.py",
    },
    "fig:scholarship-intake-bridge": {
        "filename": "scholarship_intake_bridge.png",
        "title": "Scholarship becomes intelligence only when it changes the intake",
        "caption": (
            "Source-driven bridge from four added scholarly works to the local intake. "
            "Haraway contributes standpoint and partial perspective; Jasanoff contributes "
            "framing, vulnerability, distribution, and learning; Costanza-Chock contributes "
            "participation and contestability; and D'Ignazio and Klein contribute power-aware "
            "attention to classification and invisible labor. The red gap is intentional: a "
            "source widens the operator's questions but cannot authorize an action, verify a "
            "claim, or replace affected-party testimony. The arrows are interpretive transfers, "
            "not evidence of direct influence or consensus."
        ),
        "alt": (
            "Four scholarship cards connect across a red non-authority boundary to concrete "
            "intake questions about perspective, uncertainty, contestability, classification, "
            "and hidden labor."
        ),
        "source": "docs/research-method.md, manuscript/references.bib, and manuscript/02a_global_and_historical_scholarship.md",
        "source_ids": (
            "haraway1988situated",
            "jasanoff2003humility",
            "costanzachock2020design",
            "dignazioklein2020data",
        ),
    },
    "fig:exemption-evidence-matrix": {
        "filename": "exemption_evidence_matrix.png",
        "title": "Every narrowing of a line names the evidence that must be verified first",
        "caption": (
            "Registry-derived exemption evidence-requirement matrix computed by "
            "red_line.analysis.registry_metrics.exemption_evidence_matrix. Each row "
            "is one typed exemption in the live registry, grouped under its red "
            "line; each column is one of the nine required intake dimensions. A "
            "filled cell means the exemption can narrow its line only when a "
            "VERIFIED evidence record of that kind is present; the bottom row "
            "counts how many exemptions demand each dimension. Match mode ANY or "
            "ALL states how the exemption's trigger tokens are compared with the "
            "declared scope. The matrix describes the structural shape of the "
            "author's boundaries, not their moral weight, and a satisfied evidence "
            "requirement is a locally recorded condition, not independent truth or "
            "a safety score."
        ),
        "alt": (
            f"Matrix of {_EXEMPTION_ROW_COUNT} typed exemptions against "
            f"{_EVIDENCE_KIND_COUNT} evidence kinds, with "
            "filled cells for required kinds, per-row requirement counts and match "
            "modes, and per-column demand totals."
        ),
        "source": "src/red_line/analysis/registry_metrics.py over src/red_line/registry/lines.py",
    },
    "fig:outcome-coverage-plate": {
        "filename": "outcome_coverage_plate.png",
        "title": "All five outcomes are exercised through the real evaluator, not asserted",
        "caption": (
            "Exercised outcome-coverage plate computed by "
            "red_line.analysis.outcome_coverage.run_outcome_coverage. Each row is "
            "one deterministic battery case whose ProposedAction runs through the "
            "real evaluate_action at the fixed review date; the chip on the right "
            "is the classification the evaluator actually returned, with the "
            "stable machine-readable reason codes it recorded. All five "
            "classifications are reached and every case lands on its intended "
            "outcome, which upgrades the manuscript's five-outcome claim from a "
            "control-flow assertion to a regression-pinned, executed property. "
            "Reachability is a structural property of the evaluator; the plate is "
            "not evidence that any real engagement was safe, lawful, or correctly "
            "described, and the fixture evidence records are harness fixtures, "
            "not real-world verification."
        ),
        "alt": (
            "Five battery cases, each flowing through the real evaluator to a "
            "labelled outcome chip: insufficient information, outside scope, "
            "compliant, requires modification, and non-compliant, with reason "
            "codes and a five-of-five coverage summary."
        ),
        "source": "src/red_line/analysis/outcome_coverage.py over src/red_line/evaluation/evaluator.py",
    },
    "fig:tier-monotonicity-lattice": {
        "filename": "tier_monotonicity_lattice.png",
        "title": "Dropping retained oversight never softens a verdict",
        "caption": (
            "Executed verdict-strictness lattice computed by "
            "red_line.analysis.monotonicity.run_monotonicity_sweep. Every scope "
            "keyword of every current line runs through the real evaluate_action "
            "with a fully evidenced fixture intake at all three deployment tiers "
            f"— {_MONOTONICITY.keyword_count} line/keyword slots over "
            f"{_MONOTONICITY.distinct_keyword_count} distinct tokens × "
            f"{len(_MONOTONICITY.tiers)} "
            f"tiers = {_MONOTONICITY.evaluation_count} evaluations at review date "
            f"{_MONOTONICITY.as_of} — and each chip is the classification the "
            "evaluator actually returned. Reading a row left to right moves from "
            "most to least retained oversight; strictness never decreases, and "
            f"the sweep records {_MONOTONICITY.inversion_count} inversions. The "
            "companion regression test replays the same sweep against a replica "
            "of the pre-fix defect as a positive control, so a monotone result "
            "is a pinned, falsifiable property rather than a green-by-construction "
            "assertion. Monotonicity is a consistency property of the local "
            "decision procedure exercised with fixture evidence; it is not a "
            "safety measurement, a review of any real engagement, or proof that "
            "a scope token describes a capability truthfully."
        ),
        "alt": (
            f"Lattice of {_MONOTONICITY.keyword_count} line/keyword-slot rows against "
            "the hosted, connected, and air-gapped tiers; each cell is the verdict "
            "the real evaluator returned, with strictness never decreasing as "
            f"oversight drops, {_MONOTONICITY.evaluation_count} executed runs, and "
            f"{_MONOTONICITY.inversion_count} inversions."
        ),
        "source": "src/red_line/analysis/monotonicity.py over src/red_line/evaluation/evaluator.py",
    },
    "fig:registry-composition-profile": {
        "filename": "registry_composition_profile.png",
        "title": "The shape of the boundary, line by line",
        "caption": (
            "Per-line structural profile computed by "
            "red_line.analysis.registry_metrics.line_summaries, "
            "severity_distribution, tier_floor_distribution, and "
            "unevidenced_exemptions at build time. Each row is one of the "
            f"{_LINE_COUNT} current lines in id order, carrying its severity "
            "grade and oversight floor as text-labelled chips and four counts "
            "on one shared bar scale: declared scope tokens, narrative "
            f"carve-outs, typed exemptions, and distinct evidence kinds used. "
            f"The registry splits {_SEVERITY_SPLIT} by severity and "
            f"{_FLOOR_SPLIT} by tier floor. The bottom band renders the "
            "free-pass count — typed exemptions that require no evidence at "
            f"all — which is currently {_FREE_PASS_COUNT}; it is drawn as a "
            "result rather than omitted, so a future free pass appears in the "
            "same place a zero does. Implementation fact: these are counts "
            "over registry fields. Interpretation, stated as a limit: a longer "
            "bar is a wider declared surface, not a stronger commitment, a "
            "safer practice, or a basis for comparing this author's boundary "
            "with anyone else's."
        ),
        "alt": (
            f"Table of {_LINE_COUNT} red lines with severity and tier-floor "
            "chips and four bar-and-number columns for scope tokens, carve-outs, "
            "typed exemptions, and evidence kinds, above a band reporting "
            f"{_FREE_PASS_COUNT} exemptions that require no evidence."
        ),
        "source": "src/red_line/analysis/registry_metrics.py over src/red_line/registry/lines.py",
    },
    "fig:scope-vocabulary-collisions": {
        "filename": "scope_vocabulary_collisions.png",
        "title": "Where two boundaries share a word",
        "caption": (
            "Presence grid computed by "
            "red_line.analysis.registry_metrics.scope_token_membership: every "
            f"one of the {len(_MEMBERSHIP)} distinct canonical scope tokens in "
            f"the registry against each of the {_LINE_COUNT} lines, with a "
            "filled mark where the line declares the token and a count column "
            "that repeats each row in text. Exactly "
            f"{len(_SHARED_TOKENS)} tokens ({', '.join(_SHARED_TOKENS)}) are "
            "declared by two lines; the rest belong to one line each. The "
            "footer reads out the verdict the real evaluator returned for each "
            "shared token in the tier-monotonicity sweep, so the consequence is "
            "executed rather than asserted: a shared token implicates both of "
            "its lines at once, and one line's verified exemption does not "
            "clear the other. Implementation fact: this is the declared "
            "vocabulary of the registry. Interpretation, stated as a limit: "
            "coverage remains lexical over a declared scope and is not a "
            "semantic classifier, so the grid shows which words can implicate "
            "two boundaries, never whether an action truly does."
        ),
        "alt": (
            f"Grid of {len(_MEMBERSHIP)} scope tokens against {_LINE_COUNT} red "
            "lines, with filled marks for the lines declaring each token, a "
            f"count column per row, and {len(_SHARED_TOKENS)} highlighted rows "
            "for the tokens two lines share."
        ),
        "source": "src/red_line/analysis/registry_metrics.py and src/red_line/analysis/monotonicity.py",
    },
    "fig:evidence-gate-sensitivity": {
        "filename": "evidence_gate_sensitivity.png",
        "title": "Degrade one intake dimension and the compliant result is withdrawn",
        "caption": (
            "Single-dimension perturbation sweep computed by "
            "red_line.analysis.evidence_sensitivity.run_evidence_sensitivity. A "
            f"baseline action declaring {' and '.join(_SENSITIVITY.scope)} at the "
            f"{_SENSITIVITY.tier.value} tier is classified "
            f"{_SENSITIVITY.baseline.value.upper()} with a VERIFIED record for "
            f"each of the {_EVIDENCE_KIND_COUNT} intake dimensions. Each cell then "
            "degrades exactly one of those records — removed, self-asserted, "
            "unverified, contradicted, or aged past the 180-day freshness window "
            "— and re-runs the whole action through the real evaluate_action. "
            f"All {_SENSITIVITY.evaluation_count} runs withdraw the compliant "
            f"result, and all {_SENSITIVITY.localized_count} of them name only "
            "the degraded dimension, which is the part a stop signal has to get "
            "right to be usable. Every stop is INSUFFICIENT_INFORMATION: an "
            "information gap, not a policy finding against the work. Conjunctive "
            "behaviour is a property of the local gate. It is not evidence that a "
            "VERIFIED record is true, that these are the right dimensions, or "
            "that any real intake was reviewed."
        ),
        "alt": (
            f"Grid of {_EVIDENCE_KIND_COUNT} intake dimensions against "
            f"{len(_SENSITIVITY.perturbations)} degradations, every cell reporting "
            "an insufficient-information stop with the reason codes it raised, and "
            "a trailing column confirming the gate blamed only the degraded "
            "dimension."
        ),
        "source": "src/red_line/analysis/evidence_sensitivity.py over src/red_line/evaluation/evaluator.py",
    },
    "fig:exemption-trigger-semantics": {
        "filename": "exemption_trigger_semantics.png",
        "title": "One convenient word cannot reach an ALL-mode exemption",
        "caption": (
            "Trigger-semantics probe computed by "
            "red_line.analysis.trigger_semantics.run_trigger_semantics. Each of "
            f"the {len(_TRIGGERS.rows)} typed exemptions is probed twice against a "
            "fully evidenced fixture intake: once with a single trigger token "
            "declared beside an anchor from its own line's coverage scope, and "
            "once with the whole trigger set. The left column reports how many "
            "single tokens matched and what the real evaluator returned; the right "
            f"column does the same for the full set. The {_TRIGGERS.any_mode_count} "
            "ANY-mode exemptions match on every single token, while the "
            f"{_TRIGGERS.all_mode_count} ALL-mode exemptions match on none of them "
            "and only narrow their line once every trigger token is declared — "
            f"{_TRIGGERS.evaluation_count} executed evaluate_action runs in total. "
            "A matched trigger is a declaration, never proof: the exemption still "
            "cannot narrow its line until the typed evidence it demands is "
            "VERIFIED, and the plate reports match semantics rather than whether "
            "the declaration describes the work honestly."
        ),
        "alt": (
            f"Table of {len(_TRIGGERS.rows)} typed exemptions grouped by red line, "
            "each with an ANY or ALL mode chip and two outcome chips: the verdict "
            "when one trigger token is declared and the verdict when all of them "
            "are, with ALL-mode rows blocked in the single-token column."
        ),
        "source": "src/red_line/analysis/trigger_semantics.py over src/red_line/evaluation/evaluator.py",
    },
}
